// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getScores
NumericVector getScores(IntegerVector ind, IntegerVector start_vek, IntegerVector nterm, IntegerVector freqs, IntegerVector termlist, IntegerVector rowsums, IntegerVector colsums, int ntotal, int scoretype, double laplace);
RcppExport SEXP _keyperm_getScores(SEXP indSEXP, SEXP start_vekSEXP, SEXP ntermSEXP, SEXP freqsSEXP, SEXP termlistSEXP, SEXP rowsumsSEXP, SEXP colsumsSEXP, SEXP ntotalSEXP, SEXP scoretypeSEXP, SEXP laplaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ind(indSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start_vek(start_vekSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nterm(ntermSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type termlist(termlistSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rowsums(rowsumsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type colsums(colsumsSEXP);
    Rcpp::traits::input_parameter< int >::type ntotal(ntotalSEXP);
    Rcpp::traits::input_parameter< int >::type scoretype(scoretypeSEXP);
    Rcpp::traits::input_parameter< double >::type laplace(laplaceSEXP);
    rcpp_result_gen = Rcpp::wrap(getScores(ind, start_vek, nterm, freqs, termlist, rowsums, colsums, ntotal, scoretype, laplace));
    return rcpp_result_gen;
END_RCPP
}
// genPerm
NumericMatrix genPerm(IntegerVector ind, IntegerVector start_vek, IntegerVector nterm, IntegerVector freqs, IntegerVector termlist, IntegerVector rowsums, IntegerVector colsums, int ntotal, int nperm, int output, int scoretype, NumericVector observed, double laplace);
RcppExport SEXP _keyperm_genPerm(SEXP indSEXP, SEXP start_vekSEXP, SEXP ntermSEXP, SEXP freqsSEXP, SEXP termlistSEXP, SEXP rowsumsSEXP, SEXP colsumsSEXP, SEXP ntotalSEXP, SEXP npermSEXP, SEXP outputSEXP, SEXP scoretypeSEXP, SEXP observedSEXP, SEXP laplaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ind(indSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start_vek(start_vekSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nterm(ntermSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type termlist(termlistSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rowsums(rowsumsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type colsums(colsumsSEXP);
    Rcpp::traits::input_parameter< int >::type ntotal(ntotalSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type scoretype(scoretypeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< double >::type laplace(laplaceSEXP);
    rcpp_result_gen = Rcpp::wrap(genPerm(ind, start_vek, nterm, freqs, termlist, rowsums, colsums, ntotal, nperm, output, scoretype, observed, laplace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_keyperm_getScores", (DL_FUNC) &_keyperm_getScores, 10},
    {"_keyperm_genPerm", (DL_FUNC) &_keyperm_genPerm, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_keyperm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
