#' Calculate observed keyness scores
#'
#' Calculates a vector of observed keyness scores for a given pair of corpora.
#'
#' Keyness scores are calculated for an Indexed frequency list from a given pair of corpora 
#' as generated by \code{create_ifl()}.
#' 
#' Currently, the following types of scores are supported:
#' \describe{
#'     \item{\code{llr}}{The log-likelihood ratio}
#'     \item{\code{chisq}}{The Chi-Square-Statistic}
#'     \item{\code{diff}}{Difference of relative frequencies}
#'     \item{\code{logratio}}{Binary logarithm of the ratio of the relative frequencies, possibly using a laplace correction to avoid infinite values.}
#'  }
#'  
#' @param ifl Indexed frequency list as generated by \code{create_ifl()}.
#' @param type The type of keyness measure. One of \code{llr}, \code{chisq}, \code{diff} or \code{logratio}. See details. 
#' @param laplace Parameter of laplace correction. Only relevant for \code{type = "logratio"}. See details. 
#' @return a numerical vector of the scores, one for each term. 
keyness_scores <- function(ifl, 
                          type = "llr",
                          laplace = 1.0) {
  scoretype <- switch(type,
                      llr = 1,
                      chisq = 2,
                      diff = 3,
                      logratio = 4)

  Gobs <- getScores(ind = ifl$corp_A,
                    start_vek = ifl$index$start,
                    nterm = ifl$index$nterms,
                    freqs = ifl$freqlist$freq,
                    termlist = ifl$freqlist$term,
                    rowsums = ifl$rowsums,
                    colsums = ifl$colsums,
                    ntotal = ifl$ntotal,
                    scoretype = scoretype,
                    laplace = laplace)

  Gobs

}

