# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getScores <- function(ind, start_vek, nterm, freqs, termlist, rowsums, colsums, ntotal, scoretype, laplace = 0.0) {
    .Call(`_keyperm_getScores`, ind, start_vek, nterm, freqs, termlist, rowsums, colsums, ntotal, scoretype, laplace)
}

genPerm <- function(ind, start_vek, nterm, freqs, termlist, rowsums, colsums, ntotal, nperm, output, scoretype, observed, laplace = 0.0) {
    .Call(`_keyperm_genPerm`, ind, start_vek, nterm, freqs, termlist, rowsums, colsums, ntotal, nperm, output, scoretype, observed, laplace)
}

